# Generated by Django 4.1 on 2022-08-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzeria', '0004_alter_dania_pizzeria_dodatki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dania_pizzeria',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik'),
            preserve_default=False,
        ),
    ]
