# Generated by Django 4.1 on 2022-10-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_alter_dania_pizzeria_cena_alter_dania_pizzeria_waga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dania_pizzeria',
            name='Cena',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dania_pizzeria',
            name='Rozmiar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dania_pizzeria',
            name='Waga',
            field=models.CharField(max_length=50),
        ),
    ]
