# Generated by Django 4.1 on 2022-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_alter_dania_pizzeria_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dania_pizzeria',
            name='Skladniki_DE',
            field=models.CharField(default='<Wpisz coś>', max_length=600),
        ),
        migrations.AddField(
            model_name='dania_pizzeria',
            name='Skladniki_EN',
            field=models.CharField(default='<Wpisz coś>', max_length=600),
        ),
        migrations.AddField(
            model_name='dania_pizzeria',
            name='Skladniki_PL',
            field=models.CharField(default='<Wpisz coś>', max_length=600),
        ),
        migrations.AddField(
            model_name='dania_pizzeria',
            name='Skladniki_RU',
            field=models.CharField(default='<Wpisz coś>', max_length=600),
        ),
    ]
